CREATE TABLE ACCOUNT (
	USERNAME VARCHAR(40) PRIMARY KEY,
	FULLNAME VARCHAR(40),
	BIRTH DATETIME,
	SEX CHAR(1),
	PHONE VARCHAR(10),
	EMAIL VARCHAR(40),
	PASSWORD VARCHAR(20),
	AVATAR VARCHAR(200),
	NUM_POST INT,
	NUM_FOLLOWER INT,
	NUM_FOLLOW INT,
	CAPTION VARCHAR(200),
)

UPDATE ACCOUNT
SET AVATAR = REPLACE(AVATAR, 'D:\', 'C:\')
WHERE AVATAR LIKE 'D:\%';

SELECT * FROM ACCOUNT

CREATE TABLE POST (
	MAPOST VARCHAR(10) PRIMARY KEY,
	CAPTION VARCHAR(200),
	TIMEPOST DATETIME,
	USERNAME VARCHAR(40),
	NUM_CMT INT,
	NUM_LIKE INT,
	NUM_IMAGE INT,
)

SELECT * FROM POST

CREATE TABLE IMAGEPOST(
	IMAGEPATH VARCHAR(40),
	MAPOST VARCHAR(10),
)

SELECT * FROM IMAGEPOST

UPDATE IMAGEPOST
SET IMAGEPATH = REPLACE(IMAGEPATH, 'D:\', 'C:\')
WHERE IMAGEPATH LIKE 'D:\%';


CREATE TABLE COMMENT (
	MACMT VARCHAR(10),
	USERNAME_CMT VARCHAR(40),
	CONTENT VARCHAR(40),
	MAPOST VARCHAR(10),
	USER_POST VARCHAR(40),
	TIMECMT DATETIME,
	SEEN CHAR(1),
)

SELECT * FROM COMMENT 


CREATE TABLE LIKE_STATUS (
	USERNAME_LIKE VARCHAR(40),
	MAPOST VARCHAR(10),
	USER_POST VARCHAR(40),
	TIME_LIKE DATETIME,
	SEEN CHAR(1)
)

SELECT * FROM LIKE_STATUS

CREATE TABLE NOTIFICATION (
	MANOTI VARCHAR(10) PRIMARY KEY,
	TIMENOTI DATETIME,
	LOAINOTI CHAR(1),
	MAPOST VARCHAR(10),
	CONTENT VARCHAR(40),
	USERNAME_NOTI CHAR(40),
)


CREATE TABLE ONLINE (
	USERNAME VARCHAR(40),
	FULLNAME VARCHAR(40),
	TIMEIN DATETIME,
	REMEMBER CHAR(1),
	PASSWORD VARCHAR(20),
	AVATAR VARCHAR(200),
	CAPTION VARCHAR(200),
	NUM_POST INT,
	NUM_FOLLOWER INT,
	NUM_FOLLOW INT,
)

SELECT * FROM ONLINE

CREATE TABLE REQUEST (
	USER_REQUEST VARCHAR(40),
	USER_REQUESTED VARCHAR(40),
	TIMEREQUEST DATETIME,
	SEEN CHAR(1)
)

CREATE TABLE FOLLOW (
	FOLLOWER VARCHAR(40),
	FOLLOW VARCHAR(40),
	TIMEFOLLOW DATETIME,
	SEEN CHAR(1)
)


CREATE TABLE Messed (
	Classify VARCHAR(200),
	Text VARCHAR(200),
)

SELECT * FROM Messed


